### ISSUE TITLE
0118 class issue

### ISSUE THREAD

**Issue by 106062** [106062/aboutClass#1]
- Mysql/MariaDB proxy MaxScale
- Database thread pool, connection pool
- [x] MariaDB Galera Cluster

## url

[功能](https://www.itread01.com/content/1512988748.html)
[jay](http://www.sre-devops.info/)

**Comment by mikeqoo1** [comment]
上班太無聊嗎 ^^

**Comment by 106062** [comment]
(ーー゛) 弄報告

**Comment by mikeqoo1** [comment]
哈哈 so sad

**Comment by 106062** [comment]
踩地雷分享。
更新 gitlab 版本， 從 docker 做更新。
假設當前版本為 11 要更新到最新的 13.8.1版:
步驟如下:
需要下載中間版本讓他去更新 同時還要更新 postgresql 版本，如果原本DB搭配的是MYSQL 要自行搬家到 postgresql
到 13版 DB預設為postgresql:12
可以先將DB無痛升級上去。
gitlab升級路程:
11.11.0 -> 12.0.4 -> 12.1.3 -> 12.10.4 -> 13.0.6 -> 13.2.6 

13.2.6 再跳之前 因為官方在升級過程中 為DB新增了一些擴充。 需要將 gitlab user grant with superuser。 才能升級 不然會升級失敗
